### ISSUE TITLE
Authentication Error Commenting on Post

### ISSUE THREAD

**Issue by U8NWXD** [DrewGregory/CultureMeshAndroid#137]
To reproduce:
* Create a post
* Refresh Timeline Activity
* Tap on newly created post
* Try and leave a comment

The error dialog also doesn't redirect to the login page.

**Comment by DrewGregory** [comment]
Works now. @require_api_key was our issue. We didn't include the + getCredentials(), but I removed the wrapper anyway from the backend since the api key safety is basically useless.

**Comment by U8NWXD** [comment]
So are we getting rid of the API key?
