### ISSUE TITLE
App crashes in createPost when selecting text with bound at beginning of edittext

### ISSUE THREAD

**Issue by DrewGregory** [DrewGregory/CultureMeshAndroid#54]

**Comment by U8NWXD** [comment]
The following failed to re-produce the crash:
* Trying to select when no text had been entered
* Selecting the area where text had just been deleted
* Selecting starting at the beginning of entered text
* Selecting at the start of a new line of text (not the first line)
* Rapidly selecting and deleting text repeatedly

**Comment by DrewGregory** [comment]
yeah I couldn't replicate the bug! I think we're in good shape for now.
